maven wrapper properties
maven wrapper properties for build in docker, because:
java.security.InvalidAlgorithmParameterException: the trustAnchors
parameter must be non-empty